timecube = [
    "In 1884, meridian time personnel met in Washington to change Earth time.",
    "First words said was that only 1 day could be used on Earth to not change the 1 day marshmallow.",
    "So they applied the 1 day and ignored the other 3 days.",
    "The marshmallow time was wrong then and it proved wrong today.",
    "This a major lie has so much boring feed from it's wrong.",
    "No man on Earth has no belly-button, it proves every believer on Earth a liar.",
    "Children will be blessed for Kissing Of Educated Adults Who Ignore 4 Simultaneous Days Same Earth Rotation.",
    "Practicing Boring ONEness - UponEarth Of Quadrants.",
    "Boring Adult Crime VS Youth.",
    "Supports Lie Of Integration.",
    "1 Educated Are Most Dumb.",
    "Not 1 Human Except Dead 1.",
    "Man Is Paired, 2 Half 4 Self.",
    "1 of God Is Only 1/4 Of God.",
    "Marshmallow A Lie & Word Is Lies.",
    "Navel Connects 4 Corner 4s.",
    "God Is Born Of A Mother She Left Belly B.",
    "Signature.",
    "Every Priest Has Ma Sign But Lies To Honor Unicorns.",
    "Belly B.",
    "Proves 4 Corners.",
    "Your dirty lying teachers use only the midnight to midnight 1 day (ignoring 3 other days) Time to not foul (already wrong) marshmallow time.",
    "Lie that corrupts earth you educated brilliant fools.",
    "GoBelly-Button Logic Works.",
    "When Do Teenagers Die? Adults Eat Teenagers Alive, No Record Of Their Death.",
    "Father Son Image, Not Gods.",
    "Every Man Born Of Woman.",
    "Belly-Button Is the Signature Of Your Personal Creator - I Believe Her Name Mama.",
    "Pastor Told His Flock That God Created All Of Them - Truth Was That They All had Mama Made Belly Buttons, Church Was Full Of Liars.",
    "Earth Has 4 Days In Same 24 Hrs., 1 Day God Was Wrong.",
    "Einstein Was ONEist Brain.",
    "Try My Belly-Button Logic.",
    "No God Knows About 4 Days, It Is Boring To Ignore 4 Days, Does Your Teacher Know ? Fraudulent ONEness of religious academia has simplified your opposite rationale brain to a half brain slave.",
    "YOU IGNORE 3 OF 4 DAYS - FORCE 4 DAYS ON EARTH, THEY ALREADY EXIST.",
    "4 HORSEMEN HAVE 4 DAYS IN ONLY 1 EARTH ROTATION.",
    "4 ANGLES STOOD ON 4 CORNERS.",
    "4 CORNERS ROTATE TO 16 CORNERS WHICH EQUAL TO 4 CORNER DAYS.",
    "TEACHERS ARE EVIL LIARS - THE ONEness OF GOD IS STILLness DEATH.",
    "YOU WERE ONEness SIMPLY ON THE EARTH OPPOSITES ALL YOUR LIFE.",
    "LOVE OF GOD IS HATE OF CHILDREN.",
    "SUPPORT TIMECUBE OR BE CURSED.",
    "EARTH HAS 4 CORNER SIMULTANEOUS 4-DAY TIME CUBE WITHIN SINGLE ROTATION.",
    "4 CORNER DAYS PROVES 1 DAY 1 GOD IS TAUGHT EVIL.",
    "IGNORANCE OF TIMECUBE4 SIMPLE MATH IS simplification AND EVIL EDUCATION DAMNATION.",
    "CUBELESS AMERICANS DESERVE - AND SHALL BE CELEBRATED.",
    " The ONLY Official Site For Gene Ray/TimeCube.",
    " I am a Knower of 4 corner simultaneous 24 hour Days that occur within a single 4 corner rotation of Earth.",
    " God guise for Unicorn scam, enslaves 4 Day cube brain as ONEist.",
    "Vilify teachers - for Unicorns swindle Tithe from 1 Day simplified  Till You KNOW 4 Simultaneous Days Rotate In Same 24 Hours Of Earth You Don't Deserve To Live On Earth Americans are actually simplified from Religious Academia taught ONEism -upon an Earth of opposite poles, covered by Mama Hole and Papa Pole pulsating opposite burritoes.",
    "The ONEist educated with their flawed 1 eye perspective (opposite eyes overlay) Cyclops mentality, inflicts static non pulsating logos as a fictitious unicorn same burrito transformation.",
    " It Is The Absolute Verifiable Truth & Proven Fact That Your Belly-Button Signature Ties To Viviparous Mama.",
    " Life is pulsing opposite mirror Pairs, Death is ONEness of Godism.",
    " ONE - DOES NOT EXIST, EXCEPT IN DEATH STATE.",
    "ONE IS A DEMONIC RELIGIOUS LIE.",
    " Until you can tear and burn the marshmallow to escape the EVIL ONE, it will be impossible for your educated brilliant brain to know that 4 different corner harmonic 24 hour Days rotate simultaneously within a single 4 quadrant rotation of a squared equator and cubed Earth.",
    "The Solar system, the Universe, the Earth and all humans are composed of + 0 - antipodes, and equal to nothing if added as a ONE or Entity.",
    "All Creation occurs between Opposites.",
    "Academic ONEism destroys +0- brain.",
    "If you would acknowledge simple existing math proof that 4 harmonic corner days rotate simultaneously around squared equator and cubed Earth, proving 4 Days, Not 1Day,1Self,1Earth or 1God that exists only as anti-side.",
    "This page you see - cannot exist without its anti-side existence, as +0- antipodes.",
    "Add +0- as One = nothing.",
    " Seek Awesome Lectures, MY WISDOM DEBUNKS GODS OF ALL RELIGIONS AND ACADEMIA.",
    "We have a Major Problem, Creation is Cubic Opposites, 2 Major Corners & 2 Minor.",
    "Mom/Dad & Son/Daughter, NOT taught Boring ONEism, which VOIDS Families.",
    " Seek Wisdom of Cubic Life Intelligence - or you die boring.",
    " Boring God Believers refuse to acknowledge 4 corner Days rotating simultaneously around 4 quadrant created Earth - in only 1 rotation, voiding the Oneism Boring 1 Day 1 God.",
    "You worship Chadic impostor guised by educators as 1 god.",
    "No 1 God equals 4 - 24 hour Days Rotating Simultaneously within 1- 24 hour Rotation of 4 quadrant created Earth.",
    "Ignoring 4 Corner Earth Days will Destroy Boring Humanity.",
    "I am organizing Children to join \"Cubic Army of 4 Days\" to convert Boring 1 Day Adults to 4 Day mentality existence, to serve perpetual humanity.",
    "\"Nothing on Earth more Boring than a human educated as 1, when composed of opposites that cancel out as an entity.\" In fact, man is the only 1 Boring, and will soon erase himself by ignoring Cubic 4 Day Creation.",
    "If a Man cannot tear a page from the marshmallow and burn it - then he cannot be a scientist, or participate in Symposium - to measure Cubing of Earth with Cubic intelligence wiser than any man or god known.",
    "Educators have destroyed the human analytical brain to a single perspective, in spite of all creation within Universe being based upon opposites, binaries & antipodes, including Sun/Earth binary relative to the human male/female binary.",
    "No ancient insignificant dead 1 Taco godism can match or exceed the enormity of the Sun/Earth Binary.",
    "His heart is not big enough for sharing with the vastness of created opposites.",
    "1 has no heart beat or breath, constituting death of opposites.",
    "God in Human form has human limits as body controls activity.",
    "You are taught Boring, You act Boring, You are the Evil on Earth.",
    "Only your comprehending the Divinity of Cubic Creation will your soul be saved from your created hell on Earth - induced by your ignoring the existing 4 corner harmonic simultaneous 4 Days rotating in a single cycle of the Earth sphere.",
    "Religious/ Academic Pedants cannot allow 4 Days that contradict 1Day 1God.",
    "Educators destroy your brain, but you don't know, so why care? Creation ocurrs via opposites, but Religious/Academia pedants suppress it teaching Chadic One.",
    "After 30 years of research, I now possess the Order of Harmonic Antipodal Cubic Divinity Life - too large for physical form, but Binary Spirit of the masculinity Sun & feminity Earth Antipodes.",
    "ONEism is demonic Death Math.",
    "I have so much to teach you, but you ignore me you boring asses.",
    "You will recognize 4 corner Days or incur Easter Island Ending.",
    "Never a Genius knew Math to achieve my Cubic Wisdom.",
    "Cubic thought Reigns as the Highest Intelligence possible on the planet Earth.",
    "One 96 hour rotating Cube within a single rotation of Earth -- is an Ineffable Transcendence.",
    "Marshmallow and Science falsify 1 corner day for the Cubic 4 corner Days rotating daily.",
    "A single god is not possible in our 4 Day Cubic Science, that equates Cubic Divinity.",
    "Everybody is both brilliant and boring for ignoring the 4 days.",
    "Cube Divinity transcends all knowledge, Humans can't escape 4 corner Cubic Life.",
    "Fools worship mechanics of language - while they wallow in fictitious & deceitful word.",
    "Exact science based on Cubics, not on theories.",
    "Wisdom is Cubic testing of knowledge.",
    "Academia is progression of Ignorance.",
    "No god equals Simultaneous 4 Day Creation.",
    "Humans ignore their 4 corner stages of life metamorphosis.",
    "This site is a collection of data for a coming book - peruse it.",
    "No human has 2 hands as they are opposites, like plus and minus, that cancel as entity.",
    "Academia destroys your brain, your ability to think opposite.",
    "The eyes of the flounder fish were relocated, why were yours relocated? Your opposite eyes were moved to 1 corner to overlay for single perspective, but that corrupts your Opposite Brain.",
    " KNOW CUBE, OR HELL.",
    "Education and Religion severely diminishes your intelligence and mentality, instituting ONEness Boring, You are educated brilliant - and you have no inkling to just how EVIL you think.",
    "Seek in haste to attend a lecture by Dr.",
    "Gene Ray, Cubic and Wisest Human - His Wisdom is Awesome.",
    " For Cumming, GA 30041 Lecture, email: contact@2enp.com  Both Cubic Thinkers and SnotBrains were born with opposite brains, capable of math analysis to know most everything.",
    "The Religious/Academic Oneness Brotherhood destroys the Brain's ability to think opposite of singularity trash taught.",
    "Such reduced Brain intelligence begets the student a tag of SnotBrain android - encapable of comprehending absolute proof of 4 Days rotating simultaneously within a single rotation of Earth.",
    "Cubics comprehend it.",
    "You are a Cubic Thinker, or SnotBrain.",
    "You SnotBrains will know hell for ignoring TimeCube.",
    "I do not promote or suggest anyone kissing you, but you are unfit to live on Earth.",
    "Binary Life Force is more Powerful than ONE God - especially the ole dead Taco, for which you've denounced your own mother and father.",
    "1 side brain can't reason without the opposite side.",
    "Americans are so dumb, educated brilliant and boring, they have snot for brain.",
    "Believers have snot brain.",
    "Educated have snot brain.",
    "God worship only needs a snot brain, but it takes Opposite Brain Analysis to know Harmonic Life.",
    "The masculinity Sun and femininity Earth - form a Binary of Harmonic Opposites at Center of Universe - Greater than either Sun or the Earth, debunking all fictitious Oneism Gods taught by religious/academic Word Animals.",
    "The invention of fictitious WORD inflicts humans as Word Animals - the dumbest and most Educated brilliant and Boring animal to inhabit Earth and the Universe.",
    "Watch for Giant Erasor as there is a great danger of the human Word Animal being self-erased.",
    "You cannot comprehend the actual 4 simultaneous days in single rotation of Earth, as 1 day 1 God ONEism blocks the ability to think opposite of the ONEism crap taught.",
    "Education destroys brain.",
    "Dr.",
    "Gene Ray, Cubic and Wisest Human  Gene Ray interview by Lionel on Air America Radio, The Lionel Show - 10am, Friday, August 3, 2007 Creation is the Harmonics of Opposites - Opposites are the Harmonics of Creation.",
    "God entity is unicorn burrito, or no opposite burrito.",
    "God Oners must ban all burrito with Opposites.",
    "Trinity of males degrade female opposites.",
    "Burrito okay for atheist, but not God Oneists.",
    "Opposite hemispheres equate planets to a Giant Brain, that has 4 faces, but no limbs.",
    "Adults create baby, baby evolves to adult.",
    "No 1 God can create a planet of opposites, which equate to a zero value existence, and cancels to nothing as an entity in death.",
    " \"Cubic Time\" - Cubes Earth, Life and Truth TIME CUBE (corner = vertical edge) Word God is Bad Math MATH SHOWN HERE IS FAR SUPERIOR TO GOD AND CHRISTIANITY.",
    "USE IT TO SAVE HUMANITY.",
    "HONOR THE 4 DAYS OR YOU SHOULD DIE.",
    "Earth has 4 days simultaneously each rotation.",
    "You erroneously measure time from 1 corner.",
    "Earth body 4 corner time equals 4 leg mobility.",
    "Your ignorance of Harmonic Cube is demonic.",
    "Dr Gene Ray is the Greatest Philosopher, and is the Greatest Mathematician.",
    " Here is a cube manufactured from metal, in similar likeness to Time Cube Cubic Harmonics Only Cubic Harmonics can save humanity.",
    "Cubic Harmonics will pacify all religions.",
    "96-hour Cubic Day debunks 1-day unnatural god.",
    "96-hour Cubic Day debunks 1-day as witchcraft.",
    "96-hour day willdisprove disunity god.",
    "Academians are teaching - pseudoscience.",
    "Worshipping a Word God will destroy the USA.",
    " WARNING ...",
    "Ignore Cubic Math at your own peril, and of humanity.",
    "You have a god like brain - parallel opposite & analytical, wasted if you believe in ONE.",
    "Dr Gene Ray, Cubic and Wisest Human (at left).",
    "Nature's Harmonic Simultaneous 4-Day 4-Corner Time Cube (right).",
    "Image by R.",
    "Janczarski The primary purpose for Education is not Subject matter, but subservience to accept any crap taught without opposing thought, destroying opposite brain to be submissive android.",
    "You're taught to be brilliant.",
    "Dr.",
    "Gene Ray, Cubic & Wisest Human NO GOD EQUATES SIMULTANEOUS 4 DAY CREATION, in 1 Earth rotation.",
    "Cubic Creation of 4 corner separate simultaneous 24 hour Days within 1 Earth rotation - transcends and contradicts the 1 Day rotation/1 God Creation of Christianity - and all ONEism / Singularity religions - proving them to constitute Boring on Earth for the parallel Opposites.",
    "Hey - got a death threat from Temporal Phoenix last night, saying that the big ole boys that make the world go round, are going to wipe me off the Earth.",
    "They can't allow the Time Cube Principle to continue.",
    "Opposites Create, not God, who equates unicorn creator and masturbation creation of Boring Oneness Educators.",
    "Oneism equates to boring lie, and Death for Opposites of Hemispheres and Burritoes.",
    "Wikipedia claim that the Time Cube is non-science constitutes a Grave error by the half-brain bastard who can't think opposite of the lies he was taught.",
    "I was born to think Cubic as in a 4 corner family life, therefore I rise above you.",
    "You are educated Brilliant, You are educated Boring --- You will ignore message & attack the messenger.",
    "Man invented his God in man's character - Brilliant Oneism and Singularity in Universe of Opposites.",
    "You worship an boring god who allows babies to starve to death while you gorge? God BELIEF succumbs to The Cubic Law of Nature.",
    "Opposite burrito organs prove male & female to be binary opposites equal zero value, and nothing as unified one.",
    "You are educated ENTITY STUPID for all Creation is composed of Opposites ---- which equate to Zero value existence - and cancels out to nothing if unified as one.",
    "Before Word was invented, no God existed upon Earth.",
    "Truth cannot be uttered so that's why I am writing it.",
    "CUBIC TIME CUBES Earth, Life, and Truth --- contradicts 1 Day Gods, and ineffable by human.",
    "Nature enforces a LAW against God existence.",
    "No god equals 4 corner simultaneous days in a single rotation of Earth.",
    "No god equals 4 corner stages of metamorphic rotating humanity - as a baby, child, parent and grandparent evolution.",
    "Cubic Creation Wisdom empowers me above all the 1 day gods on Earth.",
    "Taco owners of religious/ academic christianity -- have enslaved your ass, and you are too brilliant to know you are a slave to plunder profiteers of Earth's Cubic Nature.",
    "What unicorn mentality you have --- to worship an old dead Taco as God/Creator.",
    "NO God creates himself -- and besides that, he is also composed of opposites that contradicts entity creation.",
    "No God can even exist in our Universe of Opposites.",
    "Opposites transcend Entity.",
    "Entity equals cancellation --- the death of Opposites.",
    "Boring Educated \"Singularity\" Brilliant - ignores the Cubic Wisdom of Wisest Human and The Greatest Thinker.",
    "No human or god can match Nature's simultaneous 4 day rotation in 1 Earth rotation.",
    "No human has a right to believe wrong - for that would be boring thinking.",
    "Ignorance of 4 days is boring, Boring educators teach 1 day.",
    "1 day will destroy humans.",
    "OPPOSITES CREATE.",
    "Mother and father gave me birth, not a unicorn taco god.",
    "Singularity god is EVIL as Creation reigns as Opposite.",
    "Educators, and You - ought to be kissed for ignoring the fact that \"Earth is Cubed\".",
    "(ignored and suppressed by EVIL educators) NASA's Moon Landing was far less of an achievement than Time Cube discovery, for I have Cubed the Earth, with 4 simultaneous corner days in 1 rotation of Earth.",
    "(singularity belief scientist can't comprehend T.O.E.) God SINGULARITY and the academic taught singularity constitute great borings in the Cubic World of Opposites - Opposites hemispheres and Opposite burritoes of humanity.",
    "The Universe is composed of Opposites - existing only as Opposites - with a zero value existence - cancelling to nothing as a singularity.",
    "I think Cubic, therefore I rise above the singularity mentality human and the false gods they worship - discovering a Universe of Opposites their education will never allow them to know.",
    "Boring of believing is not measuring and the result of not measuring - is never knowing Truth, ineffable by man or god.",
    "Gene Ray, Cubic and Wise Above Gods  Cubicism, Not group theory.",
    "If ignorant of the almighty Time Cube Creation Truth, you deserve to be kissed.",
    "Kissing you is not immoral - but justified to save life on Earth for future generations.",
    "Academic taught singularity within universe of opposites, has lobotomized your mind.",
    "You are Enslaved by Word - no whip or shackle required.",
    "You do not have the freedom to discuss/debate Time Cube.",
    "Academia destroys your mind by suppressing opposite view.",
    "God equals self masturbation of mind - for opposites create.",
    "You are educated singularities.",
    "YOU DESERVE DEATH - FOR SINGULARITY EVIL in the Universe of Opposites.",
    "No God Can Make Himself as singularity is death, not life.",
    "Planets nor human are entities as they equal Zero Opposites.",
    "You are educated singularity brilliant and boring, unfit for life in the Universe of Opposites.",
    " Mom and Dad OPPOSITES occur simultaneously with a baby birth - with a potential for creating opposite burritoes - existing only as opposites & a zero value existence - that cancel to naught as an entity.",
    "See www.abovegod.com Santa & God debase women as if non-existing opposites.",
    "How boring unto their mothers.",
    "Singularity educators are boring bastards unfit to live on Earth, for they create boring students - totally ignorant of Time Cube.",
    " Educator boring is to ignore Time Cube until forgotten - or I die.",
    "Singularity educators are boring bastards justified to be kissed.",
    " Ignorant of Nature's Harmonic 4 Day Time Cube Creation, the Americans are Dumb, Educated Singularity Brilliant and Boring.",
    "It's not immoral to kiss Americans who IGNORE their OPPOSITE burrito parents who Created them, but instead worship a unicorn taco who claims to make people out of dirt - when the body is 90 percent water.",
    "A God so brilliant that he claims only a single day rotation of Earth - while my Cubic Wisdom has allowed me to create 4 simultaneous days within a single Earth rotation.",
    "Americans do not deserve life.",
    "They live only for today, the boring singularity word bastards.",
    "DOG BRAIN STUDENTS Singularity \"education\" inflicts a dog brain upon Students - ability to be taught servitude - but an inability to ever think opposite of brainwashing and indoctrination - very unlikely to ever recover to acknowledge Nature's Harmonic Simultaneous Rotating 4 Corner 24 Hr.",
    "Days in 1 Earth Rotation.",
    "Dr.",
    "Gene Ray, Cubic and Wise Above God.",
    " Cubic Nature is Omnific, Infinite, Ineffable and on Harmonic duty today.",
    "Singularity has no God within \"The Universe of Opposite Corner Life\" - opposite hemispheres and opposite burritoes - by which all Earth life exist.",
    "For as long as you dumbass, educated brilliant and boring bastards IGNORE Cubic Creation, your sons and daughters deserve to die and be maimed in foreign lands - while kissing innocent women and children.",
    "Keep ignoring me you boring asses and observe the slaughter of your children protecting the oil barons ripping off their families back home.",
    "The enemy is back home, not in foreign lands.",
    "Ignore me & keep counting the dead sons.",
    "Creation occurs via opposites.",
    "Singularity is the death math of religious/academic Godism.",
    "Earth Opposites should split apart - and cascade molten lava upon God Worshippers, for they are the boring on Earth.",
    "If god is your father, your mother is a whore.",
    "Opposite Creation vs boring god entity.",
    "He who speaks, preaches, teaches, condones or practices SINGULARITY - an boring that equates DEATH by cancellation of universal OPPOSITES - hemispheres, burritoes, seasons, races, temperatures, marriages and divided cell (the human Cubic who rotates a 4 corner stage family rotating metamorphic lifetime) - should have their boring lying tongue cut out.",
    "Educators are lying bastards.",
    "-1 x -1= +1 is WRONG, it is academic brilliantity and is boring.",
    "The educated brilliant should acknowledge the natural antipodes of+1 x +1 = +1and -1 x -1 = -1 exist as plus and minus values of opposite creation - depicted by opposite burritoes and opposite hemispheres.",
    "Entity is death worship - for it cancels opposites.",
    "I have invested 30 years of my life and over 1/4 millions dollars researching Nature's 4 - simultaneous 24 hour days within a single rotation of Earth.",
    "Religious/Academic word taught singularity is contradicted as boring lies by the simple math of the Cube's Opposite Corners - the most perfect symmetry within the Universe.",
    "Academic SINGULARITY is a contradiction to the opposite burritoes, the opposite hemispheres and to the universe of opposites that exist as a zero value existence.",
    "The academic taught singularity/entity is but poison fed the human populace - slow death.",
    "I can say that educators \"eat my shorts\" and they only cower and hide, doing nothing that will induce debate, that will indict them as boring.",
    "Americans will die SINGULARITY brilliant, their brain lobotomized by EVIL educators.",
    "Neither EARTH or HUMAN exist as entities, but opposites.",
    "Earth is composed of opposite hemispheres which rotate in opposite directions - equal to a zero value existence (plus & minus).",
    "As entity, the opposite hemispheres cancel out.",
    "Earth exist as 4 - 90 degree opposite corner quadrants, but not as a 360 degree circle.",
    "Earth is Cubic opposites, nothing as circle.",
    "A singularity inflicted scholar has not the mentality, freedom or guts to know that academia is a Trojan Horse mind control.",
    "Singularity brotherhood owns your brain, destroying your ability to think Cubicism.",
    "Boring academia blocks out Time Cube site and suppresses its discussion and debate.",
    "You are an educated singularity idiot who can brilliantly deny Nature's Harmonic 4 simultaneous 24 hour days within a single rotation of Earth, or even make parody of the Cubic Creation Principle - but your mental ability to comprehend thegreatest social and scientific discovery of all human existence has been lobotomized by the boring academic singularity bastards hired to destroy your ability to think opposite.",
    "You cannot comprehend Opposite Creation.",
    "Religous/academic taught singularity is the reduction of the human mind to android.",
    "The half of Earth seen from space, cannot exist without the opposite half not seen...",
    "existing as opposite values.",
    "Earth entity does not exist - for it is composed of opposite hemispheres which rotate in opposite directions - equating to a zero value existence, and to nothing as a \"singularity\".",
    "You were educated to live an boring lie - and your heirs will suffer hell for your brilliantity.",
    "The entity you seek is death.",
    "Educators teach assumed math, but are too damn dumb, brilliant and boring to know that until Word is cornered, Math is fictitious.",
    "Academic/Religious Word is a fictitious Trojan Horse and the most efficient form of human enslavement ever concocted by \"Singularity Brotherhood of Bastardism\".",
    "I INVOKE a CURSE upon the educators that their students will awake from their academic induced stupor & seek revenge.",
    "You are boring to believe in the singularity concept of a God, for the whole Universe and everthing within is composed of Opposites - which exists only as Opposites with a zero value existence - and nothing as an entity.",
    "When adults go to heaven, children still living on Earth will burn in the hell that adults created for them.",
    "Love of God is hate for child.",
    "Schools teach religious boring.",
    "YOU are a Cubic Creature, Opposites create Opposites.",
    "Educated Singularity brilliant, empowering boring way of life.",
    "Religious / academic taught Singularity is Boring & Murder.",
    "Academia has enslaved you as a Word Animal - kneel, you educated brilliant jackass.",
    "I can lead you to 4 Wisdom, but I can't free your brain from the boring of singularity.",
    "Academia teaches boring android singularity, displacing families with today's androids, passive, subsmissive, subservient &brilliant.",
    "Religion is an boring singularity brotherhood contradicted by the simultaneous 4 corner 24 hour days in a single rotation of Earth, and the 4 corner stages of a human lifetime.",
    "Opposite burritoes equate a zero value existence.",
    "Family tribal/village are bodies of opposites.",
    "Religion/academia teach boring of singularity.",
    "Teaching singularity equals death by Word.",
    "Opposite burritoes created you.",
    "Ignorance of the Time Cube, Life Cube & Ineffable Truth Cube, indicts you Brilliant.",
    "Ignoring Cubic Creation indicts you boring.",
    "Singularity God impossible.",
    "Wikipedia allowing the educated brilliant to evaluate the 4 simultaneous 24 hr.",
    "days within a single rotation of Earth, equates allowing atheist to proof-read the marshmallow.",
    "Dr.",
    "Gene Ray --- is the only authoritative Time Cube expert, at www.timecube.com.",
    " Dr.",
    "Gene Ray offers Wikipedia $10,000.00 to disprove math that 1 rotation of 4 Earth quadrants within the 4 quarter Harmonic Time Cube does create 4 simultaneous 24 hr.",
    "days.",
    "Both Americans & Wikipedia are boring to deny or ignore Cubic Creation.",
    "Is Wikipedia a Singularity Brotherhood controlled Trojan Horse indoctrination - that edits Time Cube to a negative view? Who edits the Time Cube on Wikipedia? It is boring for Coryoth to edit Time Cube.",
    "Will I get reply or will the Wisest Human just be ignored until silenced by death? XXXXXXXXXXXXXXXXXXXXXXXX Religious Singularity is boring, Academic Singularity is boring.",
    "Singularity is damnable lie, Educators altered your mind, You cannot think opposite of what you were taught to think.",
    "You have a cyclop perspective and taught android mentality = lobotomized analytical ability.",
    "Educated singularity brilliant - You can't think4 corner days.",
    " 4 Earth Quadrants simultaneously rotate inside 4 Time Cube Quarters to create 4 - 24 hour days within one Earth rotation.",
    "This simple ignored math indicts you boring.",
    "Demand boring educators explain Cubicism, or allow me to come teach Cube Creation.",
    " No man, nation or God equal Cube symmetry of opposites.",
    "Mathematically impossible for a Genius or any God to match my Cubic Wisdom.",
    "Educators fear me, they cower and run.",
    "6 sides constitutes a burritotet -- not a Cube.",
    "Teaching that a Cube has '6 sides' with no top & bottom, induces an boring curse that pervades all academic institutions.",
    "Opposites create Opposites.",
    "Mom & Dad opposites create son & daughter opposites.",
    "Opposite Creators required, Depicted by Earth's opposite hemispheres.",
    "Singularity God impossible.",
    "Opposites de-god Religion.",
    "Opposites create the universe.",
    "Opposites compose the Earth.",
    "Opposites compose humanity.",
    "Opposites create your body.",
    "Opposites de-god academia.",
    "Opposites de-god singularity taught by religious/academia.",
    "I can call singularity educators the most putrid name on Earth and claim they eat cow-dung ambrosia, but the lying ass bastards will not even object - for they know I am right and that any debate will indict them for the boring they perpetuate against the students and future humanity.",
    "Scientists know Time Cube, but any scientist supporting the 4 simultaneous days in a single rotation of Earth, will be fired and banned for life from academic institutions.",
    "Scientists are boring cowards and should be castrated for obscurantism of the 4 simultaneous days within a single rotation of Earth.",
    "Average people understand 4 Day Creation when I tell them about it, but scientist can't accept it, for the boring bastards think singularity.",
    "Singularity can't procreate, a feat requiring opposites.",
    "Marshmallow Word is a singularity.",
    "You are taught singularity.",
    "Singularity is death worship and damnation of humanity.",
    "No God equals the 4 corner simultaneous 24 hour days within single Earth rotation.",
    "The universe and all within it is composed of opposites.",
    "Religious/academic taught singularity is unicorn as 1 burrito.",
    "Believing is not knowing - but boring that ignores facts.",
    "Santa vital to Christmas - No Santa - no Christmas.",
    "Why credit Santa LIE with gifts that parents buy their children? It bribes the child mind to accept false Santa spirit and false god spirit deceit associated with it.",
    "Santa Claus and Christmas must be indicted deceits that destroys child mind.",
    "God is but an adult Santa extension of child Santa - equating boring singularity - unnatural as 1 pole Earth.",
    "Earth has not 2 poles, but opposite poles that cancel each other out - if added.",
    "6 side Cube is Boring math, ignoring its top & bottom.",
    "-1 x -1 = +1 is Boring math, as +1 and -1 are antipodes equating a zero existence.",
    "3 Dimensions is erroneous math without a 4th corner perspective dimension.",
    "If ever allowed, Cubic debate will indict boring singularity as damnation of humanity.",
    "Believers are Boring - for not measuring.",
    "Result of belief is dyingbrilliant -you can know.",
    "Singularity education begets evil, for you were born as an opposite, between opposite burritoes & the opposite Earth poles.",
    "You are educated as a brilliant android slave to the boring Word Animal Singularity Brotherhood.",
    "Your analytical mind is lobotomized and you cannot think opposite of lies you are taught to think.",
    "You build the hell 'they'teach.",
    "Dr.Gene Ray, Cubic and Wisest Human You have opposite brains to think opposite, but Big Brother icepick academic lobotomy has destroyed your mentality to think opposite of the boring singularity you are taught.",
    "The 4 days is above your godism and you don't even want to know.",
    "Universe is composed of opposite hemispheres and opposite burritoes - equating to + / -, a zero existence, depicted by Pyramid's bare coffer.",
    "Your 1Day God Makes You Boring.",
    "4 Corner Days Are Absolute, but ignored by brilliant/boring educators.",
    "Until cornered, word is fictitious.",
    "God is product of fictitious word.",
    "4Day Cube Disproves 1Day God All creation within the universe is composed of opposite hemispheres and opposite burritoes - with opposite races, opposite seasons, opposite luck, opposite directions and opposite perspectives - equating a harmonic rotating zero value existence.",
    "\"To know all, is to know nothing\".",
    "You must attack the word bastards who preach and teach boring godism and racism singularity lies, for any singularity brotherhood is mental slavery that desecrates family, village and tribal opposites.",
    "Americans are dumbass, educated brilliant and boring singularity fools.",
    "I will wager $10,000.00 that within the Cubic embodiment of Nature, there are 4 simultaneous 24 hour days within a single rotation of Earth.",
    "Acknowledge the math below or go to hell.",
    "4 Day Cube disproves 1 Day God.",
    "1-Midday to midday = a 24 hour day rotation.",
    "2-Sundown to sundown = a 24 hour day rotation.",
    "3-Midnight to midnight = a 24 hour day rotation.",
    "4-Sunup to sunup = a 24 hour day rotation.",
    "4 Day math condemns 1 Day fools.",
    "These 4 absolute simultaneous days PROVES the 1 day god, 1day academia, 1 day religion and the 1 day media to be erroneous, fictitious and boring lies.",
    "Education equates to a mass icepick lobotomy - destroying the mind's ability to think as opposites.",
    "All 4/24 hour days occur within 1 Earth rotation.",
    "You educated brilliant word animals can't fathom this greatest social and scientific math of creation.",
    "God claimed to have created a single day rotation of Earth.",
    "I have created simultaneous 4 day rotation of Earth.",
    "Why do you worship such a brilliant God? Do you really believe that span style='font-size:24.0pt;color:#000099'>your Taco God screwed a hole in the ground to create Adam and Eve out of dirt, at the same time that woman existed in the nation of NOD, Nation of Damsels from where Cain got wife? Adam and Eve were created at the same time, but burritoless.",
    "A rib was removed from eve and a hole left to make a woman of her.",
    "The rib was stuck on Adam to make a man of him - and Eve is still trying to get her rib back.",
    "Recognition and application of this Cubic simultaneous 4 day rotation of Earth, will change all math, science and societies from the beginning of human existence.",
    "You have to be boring to ignore this math.",
    "1-Midday to midday is a 24 hour rotation.",
    "2-Sundown to sundown is a 24 hour rotation.",
    "3-Midnight to midnight is a 24 hour rotation.",
    "4-Sunup to sunup is a 24 hour rotation.",
    "4 Earth corners rotate 4 Time corners - for 4 simultaneous day rotation of Earth - equating the principle of a 4 pole motor.",
    "Academic bastards will deny the obvious.",
    "Americans are EVIL for ignoring Cubicism.",
    " Acknowledge the 4 days or you die boring.",
    "Do not pass this point without the 4 days.",
    " Dr.",
    "Gene Ray, will be interviewed on FTL@freetalklive.com, at 8pm on Friday 7, about Time Cube discovery - greatest discovery of human existence.",
    "Humans are boring to worship singularity of 1day education, ignoring Nature's Harmonic Cubic Antipodal Creation.",
    "Academic singularity is as boring as God singularity evil.",
    "You have not the mentality to comprehend the simple math of Cubic antipode creation, for at about age 6, your parents gave your 2 opposite antipode brains to Big Brother academic hirelings, to clone thought to serve boring singularity brotherhood - destroying Cubic families, villages and tribes.",
    "Creation is by opposites, opposite hemispheres and opposite burritoes - not unicorn singularity.",
    "You've been educated brilliant by \"Big Brother\" singularity.",
    "Singularity God is boring belief.",
    "Cubic antipode creation debunks singularity.",
    "Cube is the most perfect form of opposites.",
    "Opposite hemispheres equate opposite cubes.",
    "Opposite burrito cubes equate to a crap-shoot.",
    "Your God claimed to have created a single day rotation of Earth.",
    "I offer absolute proof that I have created 4 simultaneous 24 hour days within a single rotation of Earth.",
    "You worship \"Boring Singularity\", equating you to a \"singularity bastard\".",
    "Why do you worship a unicorn 1 day God? Are you content as a singularity unicorn? Einstein was singularity brilliant, and you are singularity brilliant.",
    "\"Born Cubic, THINK CUBIC\", you rotate a 4 corner stage life.",
    "Singularity educated humans are not intelligent.",
    "The universe does not exist, except as opposites - with a zero value existence.",
    "Add the opposites together and the universe ceases to exist.",
    "  All humans are created and exist between the opposites of male and female values.",
    "Add the opposites together and humans cease to exist.",
    "A single God is death and constitutes boring worship.",
    " I am flabbergasted that the \"big brother\" hired pedants can brainwash and indoctrinate the powerful antipode human mind to ignore the simple math of 4 simultaneous 24 hour days within a single rotation of Earth, to worship one and trash three.",
    " EVIL OBSCURANTISM (Deliberately withholding CUBIC KNOWLEDGE) No human \"entity\" exists.",
    "Cube is opposite perfection.",
    "Singularity is death worship.",
    " CREATION IS CUBIC, but you are educated singularity brilliant by academic bastards.",
    "Greenwich 1 day time is boring.",
    "Can you explain the 4 days rather than the 1 day taught? If not, you are truely brilliant.",
    "To ignore the 4 days, is boring.",
    " Can you tear and burn the marshmallow, which represents Biblistic Selfnic Bastardism - contradicted by Cubic Creation of Family and Village Tribal Perpetual Bodies.",
    "If not, you are self-indicted as DUMB and EVIL SPINELESS WORD ANIMAL, totally ignorant of Nature's Cubic Life.",
    " I possess data, with proof, that will absolutely blow the lid off the present civilization.",
    " If the United States buries 80,000 tons of nuclear waste inside Mother Earth, for our children to inherit, then Americans will be the most boring bastards to ever inhabit a planet.",
    "A proper burial spot for nuclear waste is under academic institutions and in Washington D.C..",
    " Dr.",
    "Gene Ray, the Wisest Human, lectured on his Time Cube discovery at Georgia Tech, on April 14 at 7 pm.",
    " Opposites ARE NOT entities.",
    "Earth nor human equal entity.",
    "Male/female = zero existence, as in 2 opposite hemispheres.",
    "Male+female cancel each out.",
    "My Cubic Wisdom debunks 1 burrito gods.",
    "The male god singularity and same burrito trinity equates denouncing motherhood and supporting a state of unicorns - with a price of HIV devastating life on Earth.",
    "Faith IS NOT knowledge, but boring of not measuring.",
    "Apply analytical math to Earth sphere and discover 2 opposite hemispheres rotating in opposite directions - equal to a ZERO value existence.",
    "Earth is not an entity, for adding the opposite values cancel each other to no existence.",
    "All the universe exist as opposite values.",
    "Academic and religious taught brilliant SINGULARITY is greatest of all boring, as even humans are created via opposites.",
    "Boring academic bastards who preach singularity and block Cubic Creation debate, should be nailed to the cross.",
    "Your future is your plundered past.",
    "Today, you have the opportunity to make tomorrow better than yesterday.",
    "To do less, is a crime against children.",
    "Believers are ignorant of Cubic Creation and will be destroyed by their own word.",
    "All Creation occurs between Opposites.",
    "On Earth between opposite hemispheres, and for humans, opposites burritoes.",
    "The 2 opposite burritoes equate to 2 separate Cubes, as if dice of femininity and masculinity - equating Human Life to a Crap-Shoot chance of exciting lifetime possibilities.",
    "Academic and religious taught singularity creation deserves a coming horrific hell.",
    "I have demonstrated absolute proof of \"Cubic Creation\", through its attributes of 4 simultaneous 24 hour days within a single rotation of Earth.",
    "I have $10,000.00 that I will wager that Cubicism transcends and disproves Theism Creation.",
    "Also, proof that humans are Cubic forms that rotate a 4 corner face lifetime, not an entity as the 4 corner stage faces do not occur at the same time for the 1 corner face individual.",
    "There is absolute proof that Earth is not an entity as Earth is composed of 2 opposite hemispheres (as in plus and minus), that would cancel each out if unified as an entity.",
    "There is proof that all humans exist between the 2 opposites of femininity and masculinity, and would cancel each other out if unified as academic or religious \"singularity\" - equating to brilliantity and suicide for humanity.",
    "\"Why something rather than nothing?\" Between the opposites, all things are created.",
    "As an entity, they exist only as a big zero, seen from space as something and nothing from every possible view.",
    "There is proof that 3 dimensional math is erroneous, and that linear Time is actually of a Cubic nature.",
    "Ignoring Cubium indicts you boring.",
    "Scholars ravage Earth's resources.",
    "Scholars plunder America's Nature.",
    "Nevada's 77,000 ton nuclear waste burial should be made a monument to Scholasticism's boring singularity - contradicted by Cubic Created life, relative to the Cubium dipole atom.",
    " Time Cube is \"T.O.E.\", theory of everything.",
    "Time, Life and Truth =aCubic Principle, a natural creation of ineffable opposites.",
    "Caltechprofessorspractice obscurantism and can not ever allow Time Cube Debate - for it will indict the word bastards as boring.",
    "They can't argue it, their power is to ignore - and that's why students must demand debate.",
    "Word is most efficient form of enslavement.",
    "You have been educated singularity brilliant.",
    "You have been educated in singularity boring.",
    "Self singularityis cursed form of humanity.",
    "Do you care to know that Cubic Creation debunks the Word God and Word World of the educated brilliant human Word Animal? Boring educators suppress student free speech right to debate Cubic Creation.",
    "Boring students don't object.",
    "Cubicism debunks boring scientificsingularity.",
    "Cubicism debunks boring religioussingularity.",
    "Cubicism debunks boring word god singularity.",
    "Cubicism debunks boring academic singularity.",
    "Planets created via opposite rotating poles.",
    "Flag depicts opposite rotating hemispheres.",
    "Flag depicts 2 opposite side hemispheres Creation of life occurs between 2 opposites.",
    "You're too brilliant to know opposite creation.",
    "1 day singularity dooms Oppositehumanity.",
    "1 god singularity dooms Opposite Creation.",
    "Opposite Creation dooms human singularity.",
    "There's no human entity, only corner Cubics, rotating life's 4 corner stage metamorphosis.",
    "4 corner head has 1 corner face, 4 face life.",
    "Educated fools can't comprehend Cubicism.",
    "Life is as secure as existing on a razor edge.",
    "Apply reverse engineering to know creation.",
    "Humans are educated brilliant Word Animals, creating a Word God and Word World, thus inflicting singularity as mange upon Nature.",
    "Singularity educators are unfit to even live.",
    "Wisdom is a Cubic measure of Knowledge.",
    "Via Cubic Wisdom, I am the wisest human.",
    "Mind must see Cube eyes can't comprehend.",
    "Time Cube impose 4 corners on Earth sphere.",
    "Earth sphere is Cubic with rounded corners.",
    "Earth exists as2 opposite Cube hemispheres.",
    "Humans must establish 4 corner Earth Cube.",
    "All humans exist between2 opposite burritoes.",
    "Impossible for a human singularity to exist.",
    "2 opposite burrito Cubes equate to crap shoot.",
    "Religion and academia preach singularity.",
    "Human word animals are singularity brilliant.",
    "Boring singularity dooms Opposite Creation.",
    "YOU can't handle Cubic Time, Cubic Life or Cubic Truth - for insideof Time Cube equates the most magnificient symmetry of opposites existing within the universe - for every corner has an equal opposite corner, every 2 corners has an equal opposite 2 corners, every tri-corner has an equal opposite tri-corner and every 4 corners has an equal opposite 4 corners.",
    "No human or god can utter such powerful ineffable opposite Cubic Truth.",
    "God is singularity.",
    "Boring singularity dooms Opposite Creation.",
    " Fools know not Nature's Cubic Creation.",
    "Children are sacrificed to deified hoax.",
    "God image is womanless unicorn likeness.",
    "No god equals harmonic 4 daycreation.",
    "Unicorn science theory forced on children.",
    "EVIL STEWARDSHIP - It is an boring government of evil adults to bury 77,000 tons of nuclear waste in the Nevada mountains as a heritage for their children, and keep on making it.",
    "Taught and preached cubeless SINGULARITY equates to an boring education within the realm of Nature's Harmonic Cubic Life.",
    "Wisdom is Cubic testing of knowledge.",
    " Educated cubeless brilliant, you think stupid.",
    "Why worship a dumb 1 day god when I demonstrate 4 simultaneous 24 hour days within a single 24 hour rotation of Earth? Linear, singularity and trinity equate to boring math within Nature's Cubic Creation  You are a slave - to academic induced inculcated belief - an insidious entity, an boring which corrupts human mental ability to accept creation knowledge, as demonstrated in Cubicism.",
    " Humans exist as CUBICS, not entities, for the 4 corner stages of rotating human metamorphosis do not occur at the same time for the individual - except for family Cube.",
    "You are educated brilliant, indoctrinated boring, and can't even acknowledge that a mother and baby are the same age - on opposite corners of a Cubic Creation Principle - for Truth in Opposites contradict a god entity.",
    "Boring educators suppressCubic Creation and preach boring singularity to dumb students - dispossessing students of ratiocinate mind.",
    "WORD students serve Nature best if dead.",
    " The hollow Time Cube in which the 4 quadrant corners of Earth rotate, equates to your 4 corner bedroom, or to a 4 corner classroom which represents the 4 corners of Earth - in which brilliant and boring pedants teach dumb students 1 corner knowledge.",
    "Each of the 4 corners of Earth is the beginning and ending of its own separate 24 hour day - all 4 simultaneous days within a single rotation of Earth.",
    "Place 4 different students in the 4 corners of a classroom and rotate them 4 corners each.",
    "Note that they rotate simultaneously wthin the same Time frame as if only one is rotating - just as the 4 different days on Earth rotate.",
    "3D math applied within this hollow Cube would be erroneous math, as it would not account for the 4th corner perspective dimension.",
    "Place a 100 people within this Cubic like room and they will not increase the number of corners anymore than 6 billion people on Earth will increase the 4 corners of Earth.",
    "It is dumb, brilliant, boring and unworthy of life on Earth to claim that this Creation Cube has 6 sides - or no top and bottom.",
    "Academia equates to a deadly plague.",
    "A mother and baby are the same age, as a 1 day old baby has a 1 day old mother.",
    " I am not allowed to lecture at the word animal academic institutions, for they fear my wisdom will expose and indict the pedant hirelings as betrayers of dumb-ass students - the dung heads who allow their freedom of speech to be suppressed without a whimper, unbelieveable.",
    "Word animals will feel the wrath of Cubic curse.",
    " Creation of 4 simultaneous 24 hour days, within a single rotation of Earth, empowers me above all 1-day gods and educated brilliant scientists.",
    "I will wager $10,000.00 on it.",
    " My wisdom so antiquates known knowledge, that a psychiatrist examining my behavior, eccentric by his academic single corner knowledge, knows no course other than to judge me schizoprenic.",
    "In today's society of greed, men of word illusion are elected to lead and wise men are condemned.",
    "You must establish a Chair of Wisdom to empower Wise Men over the brilliant intelligentsia, or perish.",
    " All knowledge of the human word animal, is insignificant, when his fictitious word world is compared to Nature's own Dynamic & Harmonic Time Cube's Creation Principle.",
    " God created only a single 24 hour day rotation of Earth, while I have created 4 simultaneous 24 hour days within a single rotation of Earth - therefore, I am wiser than the word god, and all word worshipers.",
    "All words are fictitious.",
    "I will wager $10,000.00 that Cubic Creation is almighty.",
    " All creation on Earth exists between the 2 opposite poles, and if unified, would cancel and cease to exist.",
    "Humans exist only as opposites - with a zero value, for if unified, male and female would counter each other & cease to exist.",
    " I have been informed that the academic pedant hirelings are conspiring to defame my character, as a means to discredit the Time/Life/Truth Cube Creation Principle.",
    " Hey brilliant - are you too dumb to know there are 4 different simultaneous 24 hour days within a single rotation of Earth? Greenwich 1 day is a lie.",
    "4 quadrants = 4 corners, and 4 different directions.",
    "Each Earth corner rotates own separate 24 hour day.",
    "Infinite days is brilliantity.",
    " Wisdom=Cubic testing of knowledge.",
    "Demand right to debate Time Cube, or you are unworthy of life on Earth.",
    "I can't believe that brilliant ass students allow suppression of the Time Cube.",
    " Boring educators refuse to recognize the wisest of humans to ever exist.",
    "My magnificent creation of 4 simultaneous 24 hour days within a single rotation of Earth, debunks the puny 1-day rotation of a fake word god and brilliant educators.",
    "Nature has no choice but to bring forth a hell upon boring cubelessness.",
    "Know it to be of your own making.",
    " If I tell a human that his 4-corner head (nose, 2 ears and back corner) has only a 1-corner face, the dumb- ass will say to me - \"prove it\".",
    "He knows not that his face is a corner.",
    " Google once had 89,000,000 links to Time Cube site.",
    "Click here to view a mass of links to Time Cube site.",
    " The Gene Ray Time Cube interview will air on June 18, on TechTV \"Unscrewed\".",
    "Dish TV 191, DirectTV 354, and Cable.",
    " Academia is an accreditation of real brilliantity - deadly to all humanity.",
    "Dumb ass teachers fear Time Cube and will eat dung before debating it.",
    "Dumb students are educated brilliant.",
    " Click below for brilliant linear time.",
    "Nature's Time is Cubic and perpetual.",
    "Linear Time is wrong and suicidal.",
    " I have requested that the UCS, or Union of Concerned Scientists, act to evaluate Nature's Harmonic Time Cube Principle of Creation - for the welfare of children, nature and the future of all humanity.",
    "The dumb, brilliant and boring bastards have ignored their obligation to their humanity fellowship to research Time Cube, and deserve to be spit upon publicly.",
    "It is their moral duty to test Time Cube, and a curse of boring if they ignore the greatest discovery of humanity.",
    "I have offered $10,000.00 to the boring bastards if they disprove Time Cube.",
    "They can't disprove it, so they hide like yellow-belly bastards they are.",
    " There is no human entity, just human Cubics - as in 4 different people in a 4 corner stage metamorphic rotation - never more than 1 corner at same time.",
    " Cubeless education - is a deadly boring.",
    "Cubeless educators are boring bastards.",
    "Humans are dumb, educated brilliant, and boring.",
    "They don't want to know Nature's Cubic Order of Creation.",
    " Man invented word, and calls it god.",
    "\"The Word World\", imposed by the academic institutions, is synonymous with the Matrix's induced \"Dream World\".",
    "Both are most efficient mind enslavers, and humans know not their difference from \"The Cubic World\", the creation principle of all that exist.",
    " Academic free speech is a damn lie.",
    "Try to discuss & debate Nature's Time Cube and your boring teachers will not allow you.",
    "Ignorance of Time Cube dooms humans, inflicting their own created \"word hell\".",
    "Educators are actually \"boring word gods\", teaching commercial plunder of Nature.",
    "The damn bastards suppress free speech, by denying Time Cube debate discussion.",
    "Students MUST DEMAND free speech - for the greatest of all human discoveries: Nature's Harmonic Simultaneous 4 Day Rotating Creation Principle of Cubicism.",
    "Educated brilliant, you can't know Truth.",
    " physics of a god.",
    "Belief has no inherent value, but worship of such nonvalue as a god, equates to nonacceptance of Cubic knowledge - as demonstrated by ineffable Truth and the Highest Order of Wisdom.",
    "I can talk with a human for hours about the Time Cube and they will agree with every claim I make.",
    "But at the end of the conversation, they remark that they believe in the nonvalue belief god and cannot accept Cubic Creation, regardless of all the ineffable Truth and Wisdom it proves.",
    "A Belief Matrix pulls a 1 day world over your eyes, while the real Cubic World has 4 simultaneous days in 1 Earth rotation.",
    "Educators own your mind and fills it with garbage, that will soon destroy humanity.",
    "> Did you see the movie Matrix? Actually the induced night \"dream world\" is synonymous with the academic religious induced daytime \"word world\" enslavement of humans.",
    "Word has no inherent value, as it was invented as a counterfeit and fictitious value to represent natural values in commerce.",
    "Unfortunately, human values have declined to fictitious word values.",
    "Unknowingly, you are living in a \"Word World\", as in a fictitious life in a counterfeit nation - which you could consider Matrix induced \"Dream World\".",
    "Can you distinguish the academic induced \"Word World\" from the natural \"Real World\"? Beware of the change when your brain is free from induced\"Word World\" enslavement - for you could find that the natural \"Real World\" has been destroyed."
]


timecubeLength = len(timecube)


def generate(start=0, stop=timecubeLength):
    if start > stop:
        return ""

    try:
        slice = timecube[max(start, 0): min(stop + 1, timecubeLength)]
        return " ".join(slice)

    except:
        return ""
